# Generated by Django 5.1.6 on 2025-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('police_contact', models.CharField(max_length=20)),
                ('hospital_contact', models.CharField(max_length=20)),
                ('fire_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
