# Generated by Django 5.1.6 on 2025-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
