# Generated by Django 5.1.6 on 2025-04-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_incidentreport_incident_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, unique=True)),
                ('signal_state', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], max_length=50)),
                ('signal_timer', models.IntegerField()),
                ('lane_1_vehicle_count', models.IntegerField(default=0)),
                ('lane_2_vehicle_count', models.IntegerField(default=0)),
                ('lane_3_vehicle_count', models.IntegerField(default=0)),
                ('lane_4_vehicle_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type_counts', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterModelTable(
            name='incidentreport',
            table='reports_incidentreport',
        ),
    ]
