# Generated by Django 5.1.6 on 2025-04-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_trafficsignal_alter_incidentreport_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incidentreport',
            table=None,
        ),
    ]
