# Generated by Django 5.1.6 on 2025-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_incidentreport_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsignal',
            name='vehicle_type_counts',
        ),
    ]
